### ISSUE TITLE
"Non-Image content-type returned" when clicking on the link on the bottom

### ISSUE THREAD

**Issue by dtrb** [intelligent-soft-robots/pam_documentation#2]
The image is part of the link apparently. When just pasting the link into a new window, folders appear.

**Comment by dtrb** [comment]
Error on https://github.com/intelligent-soft-robots/pam_documentation. Broken image is next to the link

**Comment by vincentberenz** [comment]
solved: https://github.com/intelligent-soft-robots/pam_documentation/commit/deb377ff9fbde3feba5dbf19da579c62fd6d66d3
