### ISSUE TITLE
Do not use mpi_cmake_modules

### ISSUE THREAD

**Issue by luator** [intelligent-soft-robots/pam_documentation#5]
From what I saw, this package only contains high level documentation and nothing actual API-related.  Therefore, I suggest to not use mpi_cmake_modules for building the documentation but instead adding a basic Sphinx configuration.

Pros:
- Fewer dependencies (basically only Sphinx and maybe some plugins).
- Higher flexibility.  We can, for example, manually define the order of pages (independent of the name) and add nesting.
- It's easy to set up an automated build directly on GitHub (using the same setup as on [mw_dual_motor_torque_ctrl](https://github.com/open-dynamic-robot-initiative/mw_dual_motor_torque_ctrl)).

Cons:
- I don't see any, but maybe I am missing something?

@vincentberenz Let me know what you think.  If you agree, I'll take care of the conversion.

**Comment by vincentberenz** [comment]
@luator 

I totally agree

**Comment by luator** [comment]
Done in #6
